[build]
  command = "npm ci && npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/ffmpeg/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/ffmpeg/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/video/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/image/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/text/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 